dtb-y += e2s_eur_openx_w01_r17.dtbo
dtb-y += e2s_eur_openx_w01_r13.dtbo
dtb-y += e2s_eur_openx_w01_r11.dtbo
dtb-y += e2s_eur_openx_w01_r08.dtbo
dtb-y += e2s_eur_openx_w01_r06.dtbo
dtb-y += e2s_eur_openx_w01_r05.dtbo
dtb-y += e2s_eur_openx_w01_r04.dtbo
# SPDX-License-Identifier: GPL-2.0
always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
